### PR TITLE
Modernize test suite

### PR DESCRIPTION
**Pull request by rossmeissl**
- Make compatible with RSpec 3
- Use `let()` where appropriate
- Move to `expect` syntax (over `should`)

**Note:** It looks like a few of the integration specs need new VCR casettes! I have marked these specs as pending with `xit`.

### CODE REVIEW

**Comment by rossmeissl** [comment]
@vigosan I have a couple more PRs to submit that are branched from this (Ensemble API, Evaluation API), so I'll wait until you make a decision on this PR before submitting those.

**Comment by vigosan** [comment]
@rossmeissl thanks a lot for your help. If you want to run the specs and regenerate the cassettes, you can do it using a BigML's developer key, f.e:
1. Edit the `spec/spec_helper.rb` file, and put your `username` and `api_key` (they won't appear in the cassettes files)
2. Remove the current cassettes `rm -rf spec/vcr_cassettes`
3. Run again the full test suite by `bundle exec rspec spec`

And that's all, if the suite is green, you can commit the new cassettes.

**Comment by rossmeissl** [comment]
@vigosan there you go! Once you merge this, I'll be submitting a lot more :smile:

**Comment by vigosan** [comment]
Thanks a lot!

**Pull request merged**
